name: clang-tidy
on: [push, pull_request]
jobs:
  quickstart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-gcc@v1
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y clang-tidy
      - name: OpenMP Analysis
        run: |
          cd demo
          clang-tidy quickstart.cpp -checks=-*,openmp-* -- -I../include -std=c++17
      - name: Performance Analysis
        run: |
          cd demo
          clang-tidy quickstart.cpp -checks=-*,performance-* -- -I../include -std=c++17
      - name: CPP core guidelines
        run: |
          cd demo
          clang-tidy quickstart.cpp -checks=-*,cppcoreguidelines-* -- -I../include -std=c++17
      - name: Full Analysis
        run: |
          cd demo
          clang-tidy quickstart.cpp -checks=clang-analyzer-*,openmp-*,bugprone-*,performance-*,cppcoreguidelines-* -- -I../include -std=c++17
