name: Generate Documentation
on:
  push:
    branches:
      - master
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # doxygen is not installed by default on ubuntu images
      - name: Install doxygen
        run: sudo apt-get install doxygen
      # this should generate the documentation using Doxygen/Sphinx/Exhale
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
        python-version: 3.7
      - name: Generate documentation with Sphinx
        run: |
          cd doc/sphinx
          pip install -r requirements.txt
          make html
          cd ../.. # return to root
      # Publish built docs to gh-pages branch
      - name: Commit documentation changes
        run: |
          git clone https://github.com/bnels/BATS.git --branch gh-pages --single-branch gh-pages
          cp -r doc/sphinx/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
