name: ubuntu-latest
on: [push, pull_request]
jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-gcc@v1
      - name: Run from test directory
        run: |
          cd tests
          make test
  run-demos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: egor-tensin/setup-gcc@v1
      - name: Run quickstart demo
        run: |
          cd demo
          make quickstart.out
          ./quickstart.out
      - name: Run Rips demo
        run: |
          cd demo
          make rips.out rips_filtration.out
          ./rips.out
          ./rips_filtration.out
